"""
Django settings for face_safe_pro project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 将apps目录加入系统环境变量
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-e)(zf09nkj)s^8nt+2wpcibw^3f)55l-hg4fc6mr4yt%@w-ox'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'simplepro',
    'simpleui',
    'import_export',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'apps.public',
    'apps.account',
    'apps.device',
    'apps.archives',
    'apps.monitor'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simplepro.middlewares.SimpleMiddleware',
]

ROOT_URLCONF = 'face_safe_pro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'face_safe_pro.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# django3.2之前主键默认int类型，3.2之后默认bigint
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# 全局时间格式化
# DATETIME_FORMAT = "Y-m-d H:i:sO"
# date_format = 'Y-m-d'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


# 静态文件配置
STATIC_URL = '/static/'

# 生产环境目录
STATIC_ROOT = BASE_DIR / 'static'

# 开发阶段
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles')
]

# 图片上传配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media')

# 文件存储FastDFS_CONFIG
FAST_DFS_HOST = os.getenv('FAST_DFS_HOST', 'http://192.168.2.95')

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = True
SIMPLEUI_ANALYSIS = True

# 默认读取本地资源
SIMPLEUI_STATIC_OFFLINE = True

# 首页配置
# SIMPLEUI_HOME_TITLE = '自定义首页'
# SIMPLEUI_HOME_PAGE = 'https://www.baidu.com'
# SIMPLEUI_HOME_ICON = 'fa fa-user'
SIMPLEPRO_MONIT_DISPLAY = True
SIMPLEPRO_INFO = False

# 配置Simple Pro是否显示首页的图标，默认为True，显示图表，False不显示
SIMPLEPRO_CHART_DISPLAY = True

# SIMPLEUI_LOGO='https://mat1.gtimg.com/pingjs/ext2020/qqindex2018/dist/img/qq_logo_2x.png'


# 首页快速操作
SIMPLEUI_HOME_QUICK = True

# # 设置simpleui 点击首页图标跳转的地址
# SIMPLEUI_INDEX = 'https://www.88cto.com'

# 菜单配置后期置换
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'dynamic': False,
    'menus': [
        {
            'name': '实时监控',
            'icon': 'fa fa-desktop',
            'url': '/v1/device/real_time/',  # '/admin/device/deviceinfo/real_time/',
            # 'models': [
            #     {
            #         'name': '实时监控',
            #         'icon': 'fa fa-desktop',
            #         'url': '/admin/device/deviceinfo/real_time/'
            #     },
            #     {
            #         'name': '设备列表',
            #         'icon': 'fa fa-video',
            #         'url': '/admin/device/deviceinfo/'
            #     },
            #     {
            #         'name': '抓拍图像',
            #         'icon': 'fas fa-camera-retro',
            #         'url': '/admin/device/devicephoto/'
            #     },
            #     {
            #         'name': '报警记录',
            #         'url': '/admin/monitor/monitordiscover/'
            #     }
            # ]
        },
        {
            'name': '抓拍记录',
            'icon': 'fab fa-snapchat',
            'url': '/admin/device/devicephoto/'
        },
        {
            'name': '重点人员',
            'icon': 'fa fa-user-tie',
            'models': [
                {
                    'name': '重点人员分类',
                    'icon': 'fa fa-user-tie',
                    'url': '/admin/monitor/personneltype/'
                },
                {
                    'name': '重点人员',
                    'icon': 'fa fa-user-tie',
                    'url': '/admin/monitor/monitor/'
                },
                {
                    'name': '报警信息',
                    'icon': 'fas fa-comment',
                    'url': '/admin/monitor/monitordiscover/'
                }
            ]
        },
        {
            'name': '关注人员',
            'icon': 'fa fa-user-astronaut',
            'models': [
                {
                    'name': '人像库',
                    'icon': 'fa fa-user-astronaut',
                    'url': '/admin/monitor/archiveslibrary/'
                },
                {
                    'name': '关注人员',
                    'icon': 'fa fa-user-astronaut',
                    'url': '/admin/monitor/archivespersonnel/'
                },
                {
                    'name': '轨迹档案',
                    'icon': 'fa fa-user-astronaut',
                    'url': '/admin/monitor/photocluster/'
                }
            ],
        },
        {
            'name': '人员档案',
            'icon': 'fa fa-box',
            'models': [
                {
                    'name': '档案库',
                    'icon': 'fa fa-box',
                    'url': '/admin/archives/archivesgroup/'
                },
                {
                    'name': '档案人员',
                    'icon': 'fa fa-id-card',
                    'url': '/admin/archives/personnel/'
                },
                {
                    'name': '以人搜图',
                    'icon': 'fa fa-address-card',
                    'url': '/v1/archives/search_person/'
                }
            ],
        },
        {
            'name': '图像搜索',
            'icon': 'fa fa-search',
            'url': '/v1/device/search_image/',
            # 'models': [
            #     {
            #         'name': '以图搜图',
            #         'icon': 'fa fa-image',
            #         'url': '/admin/device/devicephoto/search_image/'
            #     },
            #     {
            #         'name': '以时间搜图',
            #         'icon': 'fas fa-clock',
            #         'url': '/admin/device/devicephoto/search_time/'
            #     }
            # ]
        },
        {
            'name': '门禁管理',
            'icon': 'fa fa-building',
            'models': [
                {
                    'name': '门禁列表',
                    'icon': 'fa fa-building',
                    'url': '/admin/monitor/restrictedarea/'
                },
                {
                    'name': '门禁通行',
                    'icon': 'fas fa-person-booth',
                    'url': '/admin/archives/accessdiscover/'
                },
                {
                    'name': '人员名单',
                    'icon': 'fas fa-child',
                    'url': '/admin/monitor/areamonitorpersonnel/'
                }
            ]
        },
        {
            'name': '重点车辆',
            'icon': 'fa fa-car',
            'models': [
                {
                    'name': '重点车辆',
                    'icon': 'fa fa-car',
                    'url': '/admin/monitor/vehiclemonitor/'
                },
                {
                    'name': '车辆报警',
                    'icon': 'fas fa-exclamation-triangle',
                    'url': '/admin/monitor/vehiclemonitordiscover/'
                }
            ]
        },
        {
            'name': '机动车管理',
            'icon': 'fa fa-bus',
            'url': '/admin/device/vehicle/'
        },
        {
            'name': '非机动车管理',
            'icon': 'fa fa-bicycle',
            'url': '/admin/device/motor/'
        },
        {
            'name': '设备管理',
            'icon': 'fab fa-whmcs',
            'url': '/admin/device/deviceinfo/'
        },
        {
            'name': '日志报警',
            'icon': 'fa fa-exclamation',
            'models': [
                {
                    'name': '事件报警',
                    'icon': 'fa fa-exclamation',
                    'url': '/admin/device/deviceoffline/'
                },
                {
                    'name': '系统日志',
                    'icon': 'far fa-bookmark',
                    'url': '/admin/admin/logentry/'
                },
            ],
        },
        {
            'name': '系统管理',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '用户管理',
                    'icon': 'fa fa-user',
                    'url': '/admin/auth/user/'
                },
                {
                    'name': '权限管理',
                    'icon': 'fas fa-shield-alt',
                    'url': '/admin/auth/permission/'
                },
                {
                    'name': '权限组管理',
                    'icon': 'fas fa-users',
                    'url': '/admin/auth/group/'
                },
            ]
        },
    ]
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.AutoSchema',
}
