# Generated by Django 3.2.13 on 2022-06-09 13:10

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivesGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "create_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "delete_at",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "create_by",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "detail",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注信息"
                    ),
                ),
                (
                    "name",
                    simplepro.components.fields.CharField(
                        max_length=32, verbose_name="库名"
                    ),
                ),
            ],
            options={
                "verbose_name": "档案库",
                "verbose_name_plural": "档案库",
                "unique_together": {("name", "delete_at")},
            },
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "create_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "delete_at",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "create_by",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "detail",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注信息"
                    ),
                ),
                (
                    "name",
                    simplepro.components.fields.CharField(
                        max_length=32, verbose_name="姓名"
                    ),
                ),
                (
                    "gender",
                    simplepro.components.fields.IntegerField(
                        choices=[(1, "男"), (2, "女"), (3, "未知")],
                        default=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "phone",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "photo",
                    simplepro.components.fields.ImageField(
                        blank=True, max_length=128, null=True, verbose_name="照片"
                    ),
                ),
                (
                    "id_card",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "household_register",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="户籍"
                    ),
                ),
                (
                    "date_of_birth",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=12, null=True, verbose_name="出生年月"
                    ),
                ),
                (
                    "nation",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="民族"
                    ),
                ),
                (
                    "nationality",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="国籍"
                    ),
                ),
                (
                    "id_type",
                    simplepro.components.fields.IntegerField(
                        choices=[(1, "身份证"), (2, "护照"), (3, "港澳居民往来内地通行证"), (4, "其他")],
                        default=1,
                        verbose_name="证件类型",
                    ),
                ),
                (
                    "id_name",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="证件名称"
                    ),
                ),
                (
                    "source",
                    simplepro.components.fields.IntegerField(
                        choices=[(0, "总控平台"), (1, "子平台")],
                        default=1,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "right_control",
                    simplepro.components.fields.IntegerField(
                        choices=[(0, "总控平台"), (1, "子平台"), (2, "总控平台， 子平台")],
                        default=2,
                        verbose_name="预警范围",
                    ),
                ),
                (
                    "address",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="住址"
                    ),
                ),
                (
                    "archives_group",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="archives.archivesgroup",
                        verbose_name="档案分组名称",
                    ),
                ),
            ],
            options={
                "verbose_name": "档案人员库",
                "verbose_name_plural": "档案人员库",
                "unique_together": {("name", "phone", "delete_at")},
            },
        ),
        migrations.CreateModel(
            name="AccessDiscover",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "create_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "delete_at",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "create_by",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "detail",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注信息"
                    ),
                ),
                (
                    "checked",
                    simplepro.components.fields.SwitchField(
                        default=False, verbose_name="已读未读"
                    ),
                ),
                (
                    "similarity",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=12, null=True, verbose_name="相似度"
                    ),
                ),
                (
                    "record",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="device.devicephoto",
                        verbose_name="通行抓拍",
                    ),
                ),
                (
                    "target",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="archives.personnel",
                        verbose_name="门禁人员档案",
                    ),
                ),
            ],
            options={
                "verbose_name": "门禁通行记录",
                "verbose_name_plural": "门禁通行记录",
            },
        ),
    ]
