# Generated by Django 3.2.13 on 2022-06-09 13:10

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpticalFiberAlarm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "create_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "delete_at",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "create_by",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "detail",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注信息"
                    ),
                ),
                (
                    "position",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=8, null=True, verbose_name="报警位置(单位 m)"
                    ),
                ),
                (
                    "createAt",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="报警时间"
                    ),
                ),
                (
                    "geo",
                    simplepro.components.fields.AMapField(
                        blank=True,
                        help_text="点击获取经纬度坐标",
                        max_length=32,
                        null=True,
                        verbose_name="经纬度坐标",
                    ),
                ),
                (
                    "channel",
                    simplepro.components.fields.IntegerField(
                        default=0, verbose_name="通道号"
                    ),
                ),
                (
                    "devIp",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="设备IP"
                    ),
                ),
                (
                    "alarmType",
                    simplepro.components.fields.IntegerField(
                        blank=True,
                        choices=[(1, "振动报警"), (2, "断纤报警")],
                        null=True,
                        verbose_name="报警类型(1: 震动 2: 断纤)",
                    ),
                ),
            ],
            options={
                "verbose_name": "光纤报警",
                "verbose_name_plural": "光纤报警",
            },
        ),
        migrations.CreateModel(
            name="RollCallHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "create_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "delete_at",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "create_by",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "detail",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注信息"
                    ),
                ),
                (
                    "start_time",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "personnel_types",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "total_person",
                    simplepro.components.fields.IntegerField(
                        default=0, verbose_name="总人数"
                    ),
                ),
                (
                    "attendance_person",
                    simplepro.components.fields.IntegerField(
                        default=0, verbose_name="已出勤人数"
                    ),
                ),
                (
                    "rate_of_attendance",
                    simplepro.components.fields.RateField(
                        default=0.0, verbose_name="出勤率"
                    ),
                ),
                (
                    "person_list",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=512, null=True, verbose_name="人员列表"
                    ),
                ),
                (
                    "person_list_record",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=512, null=True, verbose_name="人员出勤抓拍"
                    ),
                ),
            ],
            options={
                "verbose_name": "点名快照",
                "verbose_name_plural": "点名快照",
            },
        ),
        migrations.CreateModel(
            name="AlgorithmAlarm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "create_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "delete_at",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "create_by",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "detail",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注信息"
                    ),
                ),
                (
                    "back_path",
                    simplepro.components.fields.ImageField(
                        blank=True, max_length=64, null=True, verbose_name="背景照"
                    ),
                ),
                (
                    "take_photo_time",
                    simplepro.components.fields.DateTimeField(verbose_name="抓拍时间"),
                ),
                (
                    "device",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="device.deviceinfo",
                        verbose_name="报警设备",
                    ),
                ),
                (
                    "optical",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="telecom.opticalfiberalarm",
                        verbose_name="光纤报警",
                    ),
                ),
            ],
            options={
                "verbose_name": "算法报警",
                "verbose_name_plural": "算法报警",
            },
        ),
    ]
